In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

qs = pd.read_csv('/content/drive/MyDrive/qs-world-rankings-2025.csv')
the = pd.read_csv('/content/drive/MyDrive/THE World University Rankings 2016-2026.csv')

In [ ]:
qs.head()

,2025 Rank,2024 Rank,Institution Name,Location,Location Full,Size,Academic Reputation,Employer Reputation,Faculty Student,Citations per Faculty,International Faculty,International Students,International Research Network,Employment Outcomes,Sustainability,QS Overall Score
0,1,1,Massachusetts Institute of Technology (MIT),US,United States,M,100.0,100.0,100.0,100.0,99.3,86.8,96.0,100.0,99.0,100
1,2,6,Imperial College London,UK,United Kingdom,L,98.5,99.5,98.2,93.9,100.0,99.6,97.4,93.4,99.7,98.5
2,3,3,University of Oxford,UK,United Kingdom,L,100.0,100.0,100.0,84.8,98.1,97.7,100.0,100.0,85.0,96.9
3,4,4,Harvard University,US,United States,L,100.0,100.0,96.3,100.0,74.1,69.0,99.6,100.0,84.4,96.8
4,5,2,University of Cambridge,UK,United Kingdom,L,100.0,100.0,100.0,84.6,100.0,94.8,99.3,100.0,84.8,96.7

In [ ]:
qs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1503 entries, 0 to 1502
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   2025 Rank                       1503 non-null   object
 1   2024 Rank                       1482 non-null   object
 2   Institution Name                1503 non-null   object
 3   Location                        1503 non-null   object
 4   Location Full                   1503 non-null   object
 5   Size                            1503 non-null   object
 6   Academic Reputation             1503 non-null   float64
 7   Employer Reputation             1503 non-null   float64
 8   Faculty Student                 1503 non-null   float64
 9   Citations per Faculty           1503 non-null   float64
 10  International Faculty           1403 non-null   float64
 11  International Students          1445 non-null   float64
 12  International Research Network  1502 non-null   float64
 13  Employment Outcomes             1503 non-null   float64
 14  Sustainability                  1484 non-null   float64
 15  QS Overall Score                1503 non-null   object
dtypes: float64(9), object(7)
memory usage: 188.0+ KB

In [ ]:
qs.describe()

,Academic Reputation,Employer Reputation,Faculty Student,Citations per Faculty,International Faculty,International Students,International Research Network,Employment Outcomes,Sustainability
count,1503.00000,1503.000000,1503.000000,1503.000000,1403.000000,1445.000000,1502.000000,1503.000000,1484.000000
mean,20.28656,19.786693,28.128676,23.503460,30.725374,25.580346,50.129095,23.825083,24.309299
std,22.32623,23.784986,27.613017,27.870692,34.328935,31.098689,29.866588,27.351315,31.074718
min,1.30000,1.100000,1.000000,1.000000,1.000000,1.000000,1.000000,1.200000,1.000000
25%,6.30000,4.300000,7.300000,2.800000,4.200000,2.900000,22.725000,4.000000,1.300000
50%,11.00000,9.400000,16.000000,9.900000,12.500000,9.600000,51.100000,11.800000,6.750000
75%,23.50000,25.300000,40.400000,36.400000,51.600000,38.300000,77.100000,33.400000,39.500000
max,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [ ]:
the.head()

,Rank,Name,Country,Student Population,Students to Staff Ratio,International Students,Female to Male Ratio,Overall Score,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year
0,1.0,California Institute of Technology,United States,2243.0,6.9,26%,33 : 67,95.2,95.6,97.6,99.8,97.8,64.0,2016
1,2.0,University of Oxford,United Kingdom,19920.0,11.6,34%,46:54:00,94.2,86.5,98.9,98.8,73.1,94.4,2016
2,3.0,Stanford University,United States,15596.0,7.8,22%,42:58:00,93.9,92.5,96.2,99.9,63.3,76.3,2016
3,4.0,University of Cambridge,United Kingdom,18810.0,11.8,34%,46:54:00,92.8,88.2,96.7,97.0,55.0,91.5,2016
4,5.0,Massachusetts Institute of Technology,United States,11074.0,9.0,33%,37 : 63,92.0,89.4,88.6,99.7,95.4,84.0,2016

In [ ]:
the.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16713 entries, 0 to 16712
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     16713 non-null  float64
 1   Name                     16713 non-null  object
 2   Country                  16713 non-null  object
 3   Student Population       16713 non-null  object
 4   Students to Staff Ratio  16713 non-null  float64
 5   International Students   16711 non-null  object
 6   Female to Male Ratio     15953 non-null  object
 7   Overall Score            16713 non-null  float64
 8   Teaching                 16713 non-null  float64
 9   Research Environment     16713 non-null  float64
 10  Research Quality         16713 non-null  float64
 11  Industry Impact          16713 non-null  float64
 12  International Outlook    16713 non-null  float64
 13  Year                     16713 non-null  int64
dtypes: float64(8), int64(1), object(5)
memory usage: 1.8+ MB

In [ ]:
the.describe()

,Rank,Students to Staff Ratio,Overall Score,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year
count,16713.000000,16713.000000,16713.000000,16713.000000,16713.000000,16713.000000,16713.000000,16713.000000,16713.000000
mean,822.676719,18.730533,35.592513,28.593125,23.786890,49.909448,46.843965,48.121193,2021.906420
std,531.516691,15.606151,16.621830,13.931518,17.213821,26.812394,20.849752,22.619179,3.021402
min,1.000000,0.300000,8.222500,8.200000,0.800000,0.700000,0.000000,7.100000,2016.000000
25%,380.000000,12.300000,22.602500,18.900000,11.700000,26.200000,34.600000,29.300000,2020.000000
50%,760.000000,16.300000,32.730000,24.700000,17.800000,49.000000,39.700000,43.700000,2022.000000
75%,1207.000000,21.900000,45.180000,34.000000,30.100000,72.800000,57.200000,63.700000,2025.000000
max,2191.000000,865.800000,98.477500,99.200000,100.000000,100.000000,100.000000,100.000000,2026.000000

In [ ]:
qs = qs.drop_duplicates()
the = the.drop_duplicates()

In [ ]:
qs.isnull().sum()
the.isnull().sum()

Rank                         0
Name                         0
Country                      0
Student Population           0
Students to Staff Ratio      0
International Students       2
Female to Male Ratio       760
Overall Score                0
Teaching                     0
Research Environment         0
Research Quality             0
Industry Impact              0
International Outlook        0
Year                         0
dtype: int64

In [ ]:
qs['Institution Name'] = qs['Institution Name'].str.strip().str.lower()
the['Name'] = the['Name'].str.strip().str.lower()

qs['Location'] = qs['Location'].str.strip().str.lower()
the['Country'] = the['Country'].str.strip().str.lower()

In [ ]:
merged = pd.merge(
    qs,
    the,
    left_on=['Institution Name', 'Location'],
    right_on=['Name', 'Country'],
    how='outer'
)

In [ ]:
merged.head()

,2025 Rank,2024 Rank,Institution Name,Location,Location Full,Size,Academic Reputation,Employer Reputation,Faculty Student,Citations per Faculty,...,Students to Staff Ratio,International Students_y,Female to Male Ratio,Overall Score,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.9,15%,48:52:00,44.6075,25.1,28.4,73.8,43.7,71.0,2016.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.4,15%,48:52:00,48.3475,24.2,35.2,80.1,44.8,71.7,2017.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.6,13%,49:51:00,51.0450,28.2,36.2,84.2,46.5,70.7,2018.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.7,14%,NaN,53.9100,30.7,37.7,88.9,47.1,73.9,2019.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.6,15%,NaN,53.2425,28.5,39.1,87.1,48.0,75.1,2020.0

In [ ]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18216 entries, 0 to 18215
Data columns (total 30 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   2025 Rank                       1503 non-null   object
 1   2024 Rank                       1482 non-null   object
 2   Institution Name                1503 non-null   object
 3   Location                        1503 non-null   object
 4   Location Full                   1503 non-null   object
 5   Size                            1503 non-null   object
 6   Academic Reputation             1503 non-null   float64
 7   Employer Reputation             1503 non-null   float64
 8   Faculty Student                 1503 non-null   float64
 9   Citations per Faculty           1503 non-null   float64
 10  International Faculty           1403 non-null   float64
 11  International Students_x        1445 non-null   float64
 12  International Research Network  1502 non-null   float64
 13  Employment Outcomes             1503 non-null   float64
 14  Sustainability                  1484 non-null   float64
 15  QS Overall Score                1503 non-null   object
 16  Rank                            16713 non-null  float64
 17  Name                            16713 non-null  object
 18  Country                         16713 non-null  object
 19  Student Population              16713 non-null  object
 20  Students to Staff Ratio         16713 non-null  float64
 21  International Students_y        16711 non-null  object
 22  Female to Male Ratio            15953 non-null  object
 23  Overall Score                   16713 non-null  float64
 24  Teaching                        16713 non-null  float64
 25  Research Environment            16713 non-null  float64
 26  Research Quality                16713 non-null  float64
 27  Industry Impact                 16713 non-null  float64
 28  International Outlook           16713 non-null  float64
 29  Year                            16713 non-null  float64
dtypes: float64(18), object(12)
memory usage: 4.2+ MB

In [ ]:
df = merged.copy()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18216 entries, 0 to 18215
Data columns (total 30 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   2025 Rank                       1503 non-null   object
 1   2024 Rank                       1482 non-null   object
 2   Institution Name                1503 non-null   object
 3   Location                        1503 non-null   object
 4   Location Full                   1503 non-null   object
 5   Size                            1503 non-null   object
 6   Academic Reputation             1503 non-null   float64
 7   Employer Reputation             1503 non-null   float64
 8   Faculty Student                 1503 non-null   float64
 9   Citations per Faculty           1503 non-null   float64
 10  International Faculty           1403 non-null   float64
 11  International Students_x        1445 non-null   float64
 12  International Research Network  1502 non-null   float64
 13  Employment Outcomes             1503 non-null   float64
 14  Sustainability                  1484 non-null   float64
 15  QS Overall Score                1503 non-null   object
 16  Rank                            16713 non-null  float64
 17  Name                            16713 non-null  object
 18  Country                         16713 non-null  object
 19  Student Population              16713 non-null  object
 20  Students to Staff Ratio         16713 non-null  float64
 21  International Students_y        16711 non-null  object
 22  Female to Male Ratio            15953 non-null  object
 23  Overall Score                   16713 non-null  float64
 24  Teaching                        16713 non-null  float64
 25  Research Environment            16713 non-null  float64
 26  Research Quality                16713 non-null  float64
 27  Industry Impact                 16713 non-null  float64
 28  International Outlook           16713 non-null  float64
 29  Year                            16713 non-null  float64
dtypes: float64(18), object(12)
memory usage: 4.2+ MB

In [ ]:
df['Student_Population_Cleaned'] = (
    df['Student Population']
    .astype(str)
    .str.replace(',', '', regex=False)
)

df['Student_Population_Cleaned'] = pd.to_numeric(
    df['Student_Population_Cleaned'],
    errors='coerce'
)

In [ ]:
df[['Student Population', 'Student_Population_Cleaned']].head()

  Student Population  Student_Population_Cleaned
0            17422.0                     17422.0
1            19286.0                     19286.0
2            15512.0                     15512.0
3            16021.0                     16021.0
4            16340.0                     16340.0

In [ ]:
df['International_Students_y_Cleaned'] = (
    df['International Students_y']
    .astype(str)
    .str.replace('%', '', regex=False)
    .str.replace(',', '', regex=False)
)

df['International_Students_y_Cleaned'] = pd.to_numeric(
    df['International_Students_y_Cleaned'],
    errors='coerce'
)

In [ ]:
df[['International Students_y', 'International_Students_y_Cleaned']].head()

  International Students_y  International_Students_y_Cleaned
0                      15%                              15.0
1                      15%                              15.0
2                      13%                              13.0
3                      14%                              14.0
4                      15%                              15.0

In [ ]:
df['QS Overall Score'] = pd.to_numeric(
    df['QS Overall Score'],
    errors='coerce'
)

df['Global_Rank_Score'] = (
    df['QS Overall Score'].fillna(0) +
    df['Overall Score'].fillna(0)
) / 2

In [ ]:
df[['QS Overall Score',
    'Overall Score',
    'Global_Rank_Score']].head()

   QS Overall Score  Overall Score  Global_Rank_Score
0               NaN        44.6075           22.30375
1               NaN        48.3475           24.17375
2               NaN        51.0450           25.52250
3               NaN        53.9100           26.95500
4               NaN        53.2425           26.62125

In [ ]:
df['Research_Productivity_Index'] = (
    df['Research Quality'].fillna(0) +
    df['Research Environment'].fillna(0) +
    df['Citations per Faculty'].fillna(0)
) / 3

In [ ]:
df[['Research Quality',
    'Research Environment',
    'Citations per Faculty',
    'Research_Productivity_Index']].head()

,Research Quality,Research Environment,Citations per Faculty,Research_Productivity_Index
0,73.8,28.4,NaN,34.066667
1,80.1,35.2,NaN,38.433333
2,84.2,36.2,NaN,40.133333
3,88.9,37.7,NaN,42.200000
4,87.1,39.1,NaN,42.066667

In [ ]:
df['Intl_Student_Percentage'] = df['International_Students_y_Cleaned']

In [ ]:
df[['Student_Population_Cleaned',
    'International_Students_y_Cleaned',
    'Global_Rank_Score',
    'Research_Productivity_Index',
    'Intl_Student_Percentage']].describe()

,Student_Population_Cleaned,International_Students_y_Cleaned,Global_Rank_Score,Research_Productivity_Index,Intl_Student_Percentage
count,1.671300e+04,16703.000000,18216.000000,18216.000000,16703.000000
mean,2.294569e+04,11.232353,17.016916,23.184977,11.232353
std,3.268570e+04,12.181542,9.038804,13.744121,12.181542
min,2.500000e+01,0.000000,0.000000,0.333333,0.000000
25%,9.839000e+03,2.000000,10.604375,12.100000,2.000000
50%,1.741500e+04,7.000000,15.875000,21.583333,7.000000
75%,2.886000e+04,16.000000,22.281813,32.466667,16.000000
max,1.824383e+06,96.000000,50.000000,66.433333,96.000000

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[['Global_Rank_Score',
    'Research_Productivity_Index',
    'Intl_Student_Percentage']] = scaler.fit_transform(
    df[['Global_Rank_Score',
        'Research_Productivity_Index',
        'Intl_Student_Percentage']]
)

In [ ]:
df['Performance_Index'] = (
    0.4 * df['Global_Rank_Score'] +
    0.3 * df['Research_Productivity_Index'] +
    0.3 * df['Intl_Student_Percentage']
)

In [ ]:
import plotly.express as px

fig = px.bar(
    df.sort_values('Performance_Index', ascending=False).head(10),
    x='Institution Name',
    y='Performance_Index',
    title='Top 10 Universities by Performance Index'
)

fig.show()

In [ ]:
df.sort_values('Performance_Index', ascending=False)[
    ['Institution Name', 'Name', 'Performance_Index']
].head(10)

      Institution Name                     Name  Performance_Index
3962               NaN  imperial college london           0.863154
3964               NaN  imperial college london           0.856574
3963               NaN  imperial college london           0.856250
3961               NaN  imperial college london           0.836704
15152              NaN     university of oxford           0.827529
15153              NaN     university of oxford           0.824794
15151              NaN     university of oxford           0.824626
11111              NaN                      ucl           0.822742
11109              NaN                      ucl           0.821449
3960               NaN  imperial college london           0.821193

In [ ]:
df['University Name'] = df['Institution Name'].fillna(df['Name'])

In [ ]:
import plotly.express as px

fig = px.bar(
    df.sort_values('Performance_Index', ascending=False).head(10),
    x='University Name',
    y='Performance_Index',
    title='Top 10 Universities by Performance Index'
)

fig.show()

In [ ]:
merged.to_csv('/content/merged.csv', index=False)

In [ ]:
from google.colab import files
files.download('/content/merged.csv')